### ISSUE TITLE
Retirar o IbDataSet da un_CartaoEletronico

### ISSUE THREAD

**Issue by valdosouza** [valdosouza/gestaoerp#11]
Cadastro de Cartão Eletronico

Segue o padrão do Cadastro de Cargo utilizando como base baseSearch e BaseRegistry.

- [x]  Criação das Telas
           sea_electronic_card
           reg_electronic_card

- [x]  Funcionalidades

salvar a nova unit em :\gestaoerp\view\module\banking\register
[un_cartaoEletronico.zip](https://github.com/user-attachments/files/16265864/un_cartaoEletronico.zip)

**Comment by valdosouza** [comment]
Por favor Revisar esta tela, ela não está finalizada......

**Comment by rodrigoprado2305** [comment]
feito
